### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by pauline-ng** [KiddLab/QuicK-mer2#3]
Hi,

I was going through your README and this command gives a seg fault:
```
samtools view -F 3840 PATH/TO/BAM/FILE | awk '{print ">\n"$10}' | 
QuicK-mer2/quicKmer2 count -t NUMTHREADS /dev/fd/0 GENOME/REF/FASTA.fa  OUTPUT/DIR/SAMPLE_NAME
```

I got it to work by switching the stdin and ref genome arguments. I think the README instructions should instead say:

```
samtools view -F 3840 PATH/TO/BAM/FILE | awk '{print ">\n"$10}' | 
QuicK-mer2/quicKmer2 count -t NUMTHREADS  GENOME/REF/FASTA.fa  /dev/fd/0 OUTPUT/DIR/SAMPLE_NAME
```

Best,
Pauline

**Comment by jmkidd** [comment]
Thank you, you are right!  I've fixed the order in the readme.
