### ISSUE TITLE
quickmer2 count killed

### ISSUE THREAD

**Issue by pauline-ng** [KiddLab/QuicK-mer2#4]
Hi,

quickmer2 is killed after 6 hours, when trying to do the search step.

`quicKmer2 search -k 30 -t 20 -e 2 -d 100 -w 1000 -c input_GC_control_regions.bed hs37d5.fa`

![quickmer_killed](https://user-images.githubusercontent.com/10286019/106130108-f305c980-619b-11eb-9d62-8b3651541bbd.png)

Could you recommend a fix?  Alternatively, since human build 37 (hs37d5) is a popular reference genome, would it be possible to provide the k-mer file (like you did for [GRCh38 and mm10](https://kiddlabshare.med.umich.edu/QuicK-mer/QuicK-mer2-refs/))?

Thanks,
Pauline

**Comment by jmkidd** [comment]
It looks like the job was killed by your system, did you run out of memory, disk space, etc?  

I'll look into making a version for hs37d5

**Comment by pauline-ng** [comment]
I ran it on its own server and it worked.

 I had to clean up the fasta names. For example, my reference genome had :

>7 dna:chromosome

which I had to change to

>7

and then it worked.
