### ISSUE TITLE
Choose which compiler version? 

### ISSUE THREAD

**Issue by yjxbiostudy** [KiddLab/QuicK-mer2#7]
I meet a "fatal error".  Choose which compiler version?  Thanks!
 
 gcc QuicKmer.c -O3 -g -pthread -std=c99 -lm -o quicKmer2
QuicKmer.c:1:10: fatal error: math.h: No such file or directory
 #include "math.h"
          ^~~~~~~~
compilation terminated.
makefile:4: recipe for target 'make' failed
make: *** [make] Error 1

**Comment by jmkidd** [comment]
it looks like your compiler cannot find math.h files, which should be part of a standard setup.  What OS are you on?

**Comment by yjxbiostudy** [comment]
$ uname -a
Linux dell-PowerEdge-R940xa 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jmkidd** [comment]
You compiler is not setup with the required standard libraries.  You can search online for advice on proper setup of gcc and environment.  Something like:

 apt-get install build-essential

might help.


Jeff

**Comment by yjxbiostudy** [comment]
Using your suggestions, the problem I encountered was solved. If you encounter problems during compilation, try upgrading the gcc version to fix it.Nice！
